package hamroshare.ui.notes;

import hamroshare.dtos.Note;

/**
 *
 * @author Sijan Bhandari
 */
public class NoteItem extends javax.swing.JPanel {

    /**
     * Creates new form NoteItem
     */
    public NoteItem() {
        initComponents();
    }
    public NoteItem(Note note) {
        initComponents();
        title.setText(note.getTitle());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new RSMaterialComponent.RSButtonIconDos();
        delete = new RSMaterialComponent.RSButtonIconDos();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit.setBackground(new java.awt.Color(153, 153, 255));
        edit.setForeground(new java.awt.Color(255, 51, 0));
        edit.setForegroundText(new java.awt.Color(102, 51, 255));
        edit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        edit.setTypeBorder(RSMaterialComponent.RSButtonIconDos.TYPEBORDER.CIRCLE);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 50));

        delete.setBackground(new java.awt.Color(255, 153, 153));
        delete.setForeground(new java.awt.Color(255, 51, 0));
        delete.setForegroundText(new java.awt.Color(255, 0, 0));
        delete.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        delete.setTypeBorder(RSMaterialComponent.RSButtonIconDos.TYPEBORDER.CIRCLE);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 50));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Example Title");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       
    }//GEN-LAST:event_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconDos delete;
    private RSMaterialComponent.RSButtonIconDos edit;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
