package hamroshare.ui.notes;

import hamroshare.dtos.Note;
import java.awt.Cursor;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Sijan Bhandari
 */
public class NoteList extends javax.swing.JPanel {

    /**
     * Creates new form NoteList
     */
    public static NoteList noteList;
    ViewNote viewPanel;
    Rectangle rect = new Rectangle(0, 10, 310, 60);
    int ItemCount = 0;

    public NoteList() {
        initComponents();
        noteList=this;
     }

    public void RefreshNotes() {
        ArrayList<Note> notes = new ArrayList<>();
        if(notes.isEmpty()){
            EmptyNote noteItem = new EmptyNote();
            noteItem.setBounds(rect);
            add(noteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(rect.getLocation()));
        }
        for (Note note : notes) {
            NoteItem noteItem = new NoteItem(note);
            setHandCurser(noteItem);
            addClickListner(noteItem,note);
            rect.setLocation(rect.x, rect.y+(ItemCount*70));
            noteItem.setBounds(rect);
            add(noteItem,rect);
        }
    }

    public void setViewPanel(ViewNote viewPanel) {
        this.viewPanel = viewPanel;
    }

    void addClickListner(NoteItem item,Note note) {
        item.addMouseListener(new MouseListener() {
            @Override
            public void mousePressed(MouseEvent me) {
            }

            @Override
            public void mouseReleased(MouseEvent me) {
            }

            @Override
            public void mouseEntered(MouseEvent me) {
            }

            @Override
            public void mouseExited(MouseEvent me) {
            }

            @Override
            public void mouseClicked(MouseEvent me) {
                if (me.getButton() == MouseEvent.BUTTON1) {
                    viewPanel.setVisible(true);
                    viewPanel.setNote(note);
                }
                if (me.getButton() == MouseEvent.BUTTON2) {
                    //label.setText("Middle Click!");
                }
                if (me.getButton() == MouseEvent.BUTTON3) {
                    // label.setText("Right Click!");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents
void setHandCurser(JPanel panel) {
        panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
