package hamroshare.ui.notes;

import hamroshare.dtos.Note;

/**
 *
 * @author Sijan Bhandari
 */
public class ViewNote extends javax.swing.JPanel {

    /**
     * Creates new form ViewNote
     */
    public ViewNote() {
        initComponents();
    }
   public void setNote(Note note) {
        this.title.setText(note.getTitle());
        this.note.setText(note.getDetail());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new hamroshare.uicomponents.RoundPanel();
        rSScrollPane1 = new necesario.RSScrollPane();
        note = new javax.swing.JTextPane();
        noteItem1 = new hamroshare.ui.notes.NoteItem();
        rSButtonIconDos1 = new RSMaterialComponent.RSButtonIconDos();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));

        rSScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        rSScrollPane1.setColorBackground(new java.awt.Color(0, 102, 102));

        note.setBorder(null);
        note.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        rSScrollPane1.setViewportView(note);

        noteItem1.setBackground(new java.awt.Color(102, 0, 0));
        noteItem1.setForeground(new java.awt.Color(0, 102, 102));

        rSButtonIconDos1.setBackground(new java.awt.Color(153, 0, 51));
        rSButtonIconDos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconDos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconDos1ActionPerformed(evt);
            }
        });
        noteItem1.add(rSButtonIconDos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 50, 50));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Note Title");
        noteItem1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -4, 200, 60));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(noteItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(rSScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(noteItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel1Layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(rSScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconDos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconDos1ActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_rSButtonIconDos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane note;
    private hamroshare.ui.notes.NoteItem noteItem1;
    private RSMaterialComponent.RSButtonIconDos rSButtonIconDos1;
    private necesario.RSScrollPane rSScrollPane1;
    private hamroshare.uicomponents.RoundPanel roundPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
