package hamroshare.ui.notes;

import hamroshare.dtos.Note;
import hamroshare.ui.Notes;

/**
 *
 * @author Sijan Bhandari
 */
public class ViewNote extends javax.swing.JPanel {

    /**
     * Creates new form ViewNote
     */
    public ViewNote() {
        initComponents();
    }
   public void setNote(Note note) {
        this.title.setText(note.getTitle());
        this.note.setText(note.getDetail());
        Notes.noteList.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new hamroshare.uicomponents.RoundPanel();
        holder = new necesario.RSScrollPane();
        note = new javax.swing.JTextPane();
        title = new javax.swing.JLabel();
        rSButtonIconDos1 = new RSMaterialComponent.RSButtonIconDos();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));

        holder.setBackground(new java.awt.Color(102, 102, 102));
        holder.setColorBackground(new java.awt.Color(0, 102, 102));

        note.setBackground(new java.awt.Color(51, 51, 51));
        note.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        note.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        note.setForeground(new java.awt.Color(255, 255, 255));
        note.setCaretColor(new java.awt.Color(255, 255, 255));
        holder.setViewportView(note);

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Note Title");

        rSButtonIconDos1.setBackground(new java.awt.Color(153, 0, 51));
        rSButtonIconDos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconDos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconDos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonIconDos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSButtonIconDos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel1Layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconDos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconDos1ActionPerformed
      this.setVisible(false);
      Notes.noteList.setVisible(true);
    }//GEN-LAST:event_rSButtonIconDos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSScrollPane holder;
    private javax.swing.JTextPane note;
    private RSMaterialComponent.RSButtonIconDos rSButtonIconDos1;
    private hamroshare.uicomponents.RoundPanel roundPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
