package hamroshare.ui;

import hamroshare.config.HamroFetcher;
import hamroshare.config.HamroPath;
import hamroshare.eventhandlers.Info;
import hamroshare.login.LoginController;
import hamroshare.ui.popup.Message;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Sijan Bhandari
 */
public class AddTransaction extends javax.swing.JPanel {

    /**
     * Creates new form AddTransaction
     */
    Profile profile;
    public AddTransaction() {
        initComponents();
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new hamroshare.uicomponents.RoundPanel();
        firstStep = new javax.swing.JPanel();
        panel2 = new hamroshare.ui.AddTransactionNext();
        jLabel1 = new javax.swing.JLabel();
        rSButtonMaterialRipple1 = new RSMaterialComponent.RSButtonMaterialRipple();
        rSButtonMaterialUno1 = new RSMaterialComponent.RSButtonMaterialUno();

        setBackground(new java.awt.Color(51, 51, 51));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstStep.setBackground(new java.awt.Color(51, 51, 51));
        firstStep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        firstStep.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 310, 180));

        roundPanel1.add(firstStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Transaction");
        roundPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 60));

        rSButtonMaterialRipple1.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonMaterialRipple1.setText("Cancel");
        rSButtonMaterialRipple1.setBackgroundHover(new java.awt.Color(204, 0, 0));
        rSButtonMaterialRipple1.setBorderPainted(false);
        rSButtonMaterialRipple1.setFocusPainted(false);
        rSButtonMaterialRipple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialRipple1ActionPerformed(evt);
            }
        });
        roundPanel1.add(rSButtonMaterialRipple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, -1));

        rSButtonMaterialUno1.setBackground(new java.awt.Color(0, 204, 153));
        rSButtonMaterialUno1.setText("Continue");
        rSButtonMaterialUno1.setBackgroundHover(new java.awt.Color(0, 102, 0));
        rSButtonMaterialUno1.setBorderPainted(false);
        rSButtonMaterialUno1.setFocusPainted(false);
        rSButtonMaterialUno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialUno1ActionPerformed(evt);
            }
        });
        roundPanel1.add(rSButtonMaterialUno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 160, -1));

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialUno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialUno1ActionPerformed
        new AddStock(this).start();

    }//GEN-LAST:event_rSButtonMaterialUno1ActionPerformed

    private void rSButtonMaterialRipple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialRipple1ActionPerformed
        this.setVisible(false);
        profile.jtab.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialRipple1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstStep;
    private javax.swing.JLabel jLabel1;
    private hamroshare.ui.AddTransactionNext panel2;
    private RSMaterialComponent.RSButtonMaterialRipple rSButtonMaterialRipple1;
    private RSMaterialComponent.RSButtonMaterialUno rSButtonMaterialUno1;
    private hamroshare.uicomponents.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
class AddStock extends Thread {
        JPanel panel;
        public AddStock(JPanel panel) {
            this.panel = panel;
        }

        @Override
        public void run() {
                if (panel2.getPrice().equals("") || panel2.getUnits().equals("") || panel2.getCompany().equals("Select Company")) {
                    Info.display(panel, "Enter Required data", 0, 2000);
                } else {
                    try {
                        System.out.println(panel2.getCompany());
                        URL url = new URL(HamroPath.ApiHome+"/user/portfolio/addstock/"
                                + LoginController.userDto.getId() + "/"
                                + panel2.getCompany() + "/"
                                + Integer.parseInt(panel2.getUnits()) + "/"
                                + Double.parseDouble(panel2.getPrice()));
                        System.out.println(url);
                        String json1 = HamroFetcher.getData(url.toString());
                        System.out.println(json1);
                        panel.setVisible(false);
                        profile.jtab.setVisible(true);
                        profile.refreshData();
                        Message me=new Message(Dash.dash,true);
                        me.setMessages("Purchased: "+panel2.getCompany(), "Cost: "+json1);
                        me.showAlert();
                    } catch (Exception ex) {
                        Info.display(panel, "Details Error", 0, 2000);
                        Logger.getLogger(AddTransaction.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
    }
}
