package hamroshare.ui;

import com.fasterxml.jackson.databind.ObjectMapper;
import hamroshare.config.HamroFetcher;
import hamroshare.config.HamroPath;
import hamroshare.dtos.CompanyDto;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sijan Bhandari
 */
public final class AddTransactionNext extends javax.swing.JPanel {

    /**
     * Creates new form AddTransactionNext
     */
    public AddTransactionNext() {
        initComponents();
        updateCompanyList();
    }
    public String getUnits(){
        return units.getText();
    }
    public String getPrice(){
        return buyprice.getText();
    }
    public String getCompany(){
         return comboBox.getSelectedItem().toString();
    }
    public void updateCompanyList(){
        new CompanyList().start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyprice = new RSMaterialComponent.RSTextFieldMaterial();
        units = new RSMaterialComponent.RSTextFieldMaterial();
        comboBox = new rojerusan.RSComboBox();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buyprice.setBackground(new java.awt.Color(51, 51, 51));
        buyprice.setForeground(new java.awt.Color(255, 255, 255));
        buyprice.setCaretColor(new java.awt.Color(255, 255, 255));
        buyprice.setColorMaterial(new java.awt.Color(255, 255, 255));
        buyprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buyprice.setPhColor(new java.awt.Color(255, 255, 255));
        buyprice.setPlaceholder("Buying price Rs.");
        buyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buypriceActionPerformed(evt);
            }
        });
        add(buyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 50));

        units.setBackground(new java.awt.Color(51, 51, 51));
        units.setForeground(new java.awt.Color(255, 255, 255));
        units.setCaretColor(new java.awt.Color(255, 255, 255));
        units.setColorMaterial(new java.awt.Color(255, 255, 255));
        units.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        units.setPhColor(new java.awt.Color(255, 255, 255));
        units.setPlaceholder("Units");
        units.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitsActionPerformed(evt);
            }
        });
        add(units, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        comboBox.setBackground(new java.awt.Color(51, 51, 51));
        comboBox.setForeground(new java.awt.Color(0, 0, 0));
        add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buypriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buypriceActionPerformed

    private void unitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTextFieldMaterial buyprice;
    private rojerusan.RSComboBox comboBox;
    public RSMaterialComponent.RSTextFieldMaterial units;
    // End of variables declaration//GEN-END:variables
class CompanyList extends Thread{
    @Override
    public void run(){
        String url=HamroPath.ApiHome+"/company/list";
        try {
            String json = HamroFetcher.getData(url);
            CompanyDto[] companies=new ObjectMapper().readValue(json, CompanyDto[].class);
            comboBox.removeAllItems();
            comboBox.addItem("Select Company");
            for(CompanyDto dto:companies){
                comboBox.addItem(dto.getSymbol());
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(AddTransactionNext.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AddTransactionNext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
}
