
package hamroshare.ui;
/**
 *
 * @author Sijan Bhandari
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Dash1
     */
    public Home() {
        initComponents();
        //dashpanel.setLayout(new MigLayout("content, fillx, inset 3", "[fill]", "[]0[]"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index4 = new javax.swing.JLabel();
        dashpanel = new hamroshare.uicomponents.RoundPanel();
        gauch = new hamroshare.uicomponents.GaugeChart();
        percentage = new javax.swing.JLabel();
        positivityText = new javax.swing.JLabel();
        nepseName = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        change = new javax.swing.JLabel();

        index4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        index4.setForeground(new java.awt.Color(255, 255, 255));
        index4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        index4.setText("Change Percentage: 3500");

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashpanel.setBackground(new java.awt.Color(51, 51, 51));
        dashpanel.setPreferredSize(new java.awt.Dimension(162, 418));
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gauch.setBackground(new java.awt.Color(0, 0, 0));
        gauch.setForeground(new java.awt.Color(0, 255, 204));
        gauch.setColor1(new java.awt.Color(255, 0, 0));
        gauch.setColor2(new java.awt.Color(0, 153, 0));
        gauch.setGaugeSize(7);
        gauch.setValue(60);
        dashpanel.add(gauch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 270, 150));

        percentage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        percentage.setForeground(new java.awt.Color(255, 255, 255));
        percentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashpanel.add(percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 40));

        positivityText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        positivityText.setForeground(new java.awt.Color(255, 255, 255));
        positivityText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positivityText.setText("Market Positivity");
        dashpanel.add(positivityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 70));

        nepseName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nepseName.setForeground(new java.awt.Color(255, 255, 255));
        nepseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nepseName.setText("Nepse");
        dashpanel.add(nepseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 40));

        value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        value.setForeground(new java.awt.Color(255, 255, 255));
        value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashpanel.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 40));

        change.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashpanel.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 40));

        add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 272, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel change;
    private hamroshare.uicomponents.RoundPanel dashpanel;
    public static hamroshare.uicomponents.GaugeChart gauch;
    private javax.swing.JLabel index4;
    public static javax.swing.JLabel nepseName;
    public static javax.swing.JLabel percentage;
    public static javax.swing.JLabel positivityText;
    public static javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
