package hamroshare.ui;

import dataalgorithms.SearchDataAlgo;
import hamroshare.uicomponents.ScrollBarCustom;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Sijan Bhandari
 */
public class LiveTable extends javax.swing.JPanel {

    /**
     * Creates new form Dash1
     */
    public LiveTable() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        tbl.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        ScrollBarCustom sb = new ScrollBarCustom();
        sb.setForeground(Color.white);
        sp1.setVerticalScrollBar(sb);
        //sp1.setLayout(new MigLayout("wrap, fillx, inset 3", "[fill]", "[]0[]"));
        sp1.setBackground(new Color(100, 0, 0, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new hamroshare.uicomponents.RoundPanel();
        sp1 = new javax.swing.JScrollPane();
        tbl = new rojerusan.RSTableMetro();
        srchText = new rojeru_san.rsfield.RSTextMaterial();
        date = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sp1.setForeground(new java.awt.Color(51, 51, 51));
        sp1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sp1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sp1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sp1.setEnabled(false);
        sp1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                sp1ComponentResized(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Symbol", "Market Price", "Change", "Difference"
            }
        ));
        tbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl.setAutoscrolls(false);
        tbl.setEnabled(false);
        tbl.setFocusable(false);
        sp1.setViewportView(tbl);

        roundPanel1.add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 390, 390));

        srchText.setBackground(new java.awt.Color(51, 51, 51));
        srchText.setForeground(new java.awt.Color(255, 255, 255));
        srchText.setColorMaterial(new java.awt.Color(255, 255, 255));
        srchText.setPlaceholder("Search Company");
        srchText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                srchTextCaretUpdate(evt);
            }
        });
        roundPanel1.add(srchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 30));

        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roundPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 220, 30));

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, 390, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void sp1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sp1ComponentResized
        tbl.scrollRectToVisible(tbl.getCellRect(0, 0, true));
    }//GEN-LAST:event_sp1ComponentResized

    private void srchTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_srchTextCaretUpdate
        String key = srchText.getText();
        SearchDataAlgo.displayToTable(key);
    }//GEN-LAST:event_srchTextCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel date;
    private hamroshare.uicomponents.RoundPanel roundPanel1;
    private javax.swing.JScrollPane sp1;
    private rojeru_san.rsfield.RSTextMaterial srchText;
    public static rojerusan.RSTableMetro tbl;
    // End of variables declaration//GEN-END:variables
}

class MyTableCellRenderer extends DefaultTableCellRenderer {

    @Override
    public Color getBackground() {
        return super.getBackground();
    }
}
