package hamroshare.ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Sijan Bhandari
 */
public class LoadingPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadingPanel
     */
    public LoadingPanel() {
        initComponents();
        try {
            //jLabel1.setHorizontalTextPosition( JLabel.LEADING );
            ImageIcon imageIcon = new ImageIcon(ImageIO.read(LoadingPanel.class.getClassLoader().getResourceAsStream("icon/coin.gif")));
            jLabel1.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(LoadingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loading From Server");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 42, 240, 190));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
