package hamroshare.ui;

import hamroshare.dtos.StockPortfolioDto;
import java.awt.Color;
import rojeru_san.efectos.ValoresEnum;

/**
 *
 * @author Sijan Bhandari
 */
public class StockPortfolio extends javax.swing.JPanel {

    /**
     * Creates new form StockPortfolio
     */
    public StockPortfolioDto port;
    public StockPortfolio() {
        initComponents();
        sellpanel.setVisible(false);
    }
    public StockPortfolio(String name) {
        initComponents();
        sname.setText(name);
        sellpanel.setVisible(false);
    }
    public void refreshData(){
        
    }
    public StockPortfolio(StockPortfolioDto port){
        this.port=port;
        initComponents();
        sellpanel.setVisible(false);
        sname.setText(port.getName());
        kitta.setText(port.getKitta()+" Kitta");
        portfoliovalue.setText("NPR "+port.getTotal());
        purchasecost.setText("NPR "+port.getPurchasePrice());
        todayPrice.setText("NPR "+port.getTodayPrice());
        overallgainloss.setText("NPR "+Math.round(Double.parseDouble(port.getTotalGainOrLoss())));
        todaygainloss.setText("NPR "+Math.round(Double.parseDouble(port.getTodayGainOrLoss()) * 100.0) / 100.0);
        if (Double.parseDouble(port.getTotalGainOrLoss()) < 0) {
                overallgainloss.setForeground(new Color(255, 0, 51));
                overarrow.setForegroundText(new Color(255, 0, 51));
                overarrow.setIcons(ValoresEnum.ICONS.ARROW_DROP_DOWN);
            }
            else if (Double.parseDouble(port.getTotalGainOrLoss()) > 0) {
                overallgainloss.setForeground(new Color(0, 255, 0));
                overarrow.setForegroundText(new Color(0, 255, 0));
                overarrow.setIcons(ValoresEnum.ICONS.ARROW_DROP_UP);
            }
            else {
                overallgainloss.setForeground(new Color(255, 255, 0));
                overarrow.setForegroundText(new Color(255, 255, 0));
                overarrow.setIcons(ValoresEnum.ICONS.PLAY_ARROW);
            }
            if (Double.parseDouble(port.getTodayGainOrLoss()) < 0) {
                todaygainloss.setForeground(new Color(255, 0, 51));
                todayarrow.setForegroundText(new Color(255, 0, 51));
                todayarrow.setIcons(ValoresEnum.ICONS.ARROW_DROP_DOWN);
            } else if ((Double.parseDouble(port.getTodayGainOrLoss()) > 0)) {
                todaygainloss.setForeground(new Color(0, 255, 0));
                todayarrow.setForegroundText(new Color(0, 255, 0));
                todayarrow.setIcons(ValoresEnum.ICONS.ARROW_DROP_UP);
            } else {
                todaygainloss.setForeground(new Color(255, 255, 0));
                todayarrow.setForegroundText(new Color(255, 255, 0));
                todayarrow.setIcons(ValoresEnum.ICONS.PLAY_ARROW);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sellpanel = new hamroshare.ui.Sellpanel();
        rSButtonRound1 = new rojeru_san.rsbutton.RSButtonRound();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        overarrow = new RSMaterialComponent.RSButtonIconUno();
        todayarrow = new RSMaterialComponent.RSButtonIconUno();
        todaygainloss = new javax.swing.JLabel();
        overallgainloss = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kitta = new javax.swing.JLabel();
        portfoliovalue = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        purchasecost = new javax.swing.JLabel();
        todayPrice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(sellpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 350, 290));

        rSButtonRound1.setText("Sell");
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 60, 40));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TODAY'S GAIN/LOSS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 153));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 5));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 320, 60));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 180, 60));

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, 60));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 153));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 5));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 320, 60));

        overarrow.setBackground(new java.awt.Color(51, 51, 51));
        overarrow.setForeground(new java.awt.Color(0, 255, 0));
        overarrow.setForegroundText(new java.awt.Color(255, 51, 0));
        overarrow.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_DROP_DOWN);
        add(overarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 20, 40));

        todayarrow.setBackground(new java.awt.Color(51, 51, 51));
        todayarrow.setForeground(new java.awt.Color(0, 255, 0));
        todayarrow.setForegroundText(new java.awt.Color(51, 255, 0));
        todayarrow.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_DROP_UP);
        add(todayarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 20, 40));

        todaygainloss.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todaygainloss.setForeground(new java.awt.Color(0, 255, 0));
        todaygainloss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todaygainloss.setText("NPR 21,34,344");
        add(todaygainloss, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 30));

        overallgainloss.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        overallgainloss.setForeground(new java.awt.Color(255, 0, 51));
        overallgainloss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overallgainloss.setText("NPR 21,34,344");
        add(overallgainloss, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, 30));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("OVERALL PROFIT");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 20));

        kitta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kitta.setForeground(new java.awt.Color(0, 204, 204));
        kitta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitta.setText("100 Kitta");
        add(kitta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 20));

        portfoliovalue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        portfoliovalue.setForeground(new java.awt.Color(255, 255, 255));
        portfoliovalue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portfoliovalue.setText("NPR 21,34,344");
        add(portfoliovalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 40));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PURCHASE COST");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 20));

        purchasecost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        purchasecost.setForeground(new java.awt.Color(0, 204, 204));
        purchasecost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasecost.setText("NPR 21,34,344");
        add(purchasecost, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 30));

        todayPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todayPrice.setForeground(new java.awt.Color(0, 204, 204));
        todayPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todayPrice.setText("NPR 21,34,344");
        add(todayPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 150, 30));

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TODAY'S PRICE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 20));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Worth");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 340, 20));

        sname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sname.setForeground(new java.awt.Color(255, 255, 255));
        sname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sname.setText("Stock Name");
        add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
    sellpanel.SellMe(this);
    }//GEN-LAST:event_rSButtonRound1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel kitta;
    private javax.swing.JLabel overallgainloss;
    private RSMaterialComponent.RSButtonIconUno overarrow;
    private javax.swing.JLabel portfoliovalue;
    private javax.swing.JLabel purchasecost;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound1;
    private hamroshare.ui.Sellpanel sellpanel;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel todayPrice;
    private RSMaterialComponent.RSButtonIconUno todayarrow;
    private javax.swing.JLabel todaygainloss;
    // End of variables declaration//GEN-END:variables
}
