
package hamroshare.components;

/**
 *
 * @author Sijan Bhandari
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Dash1
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashpanel = new hamroshare.customswings.RoundPanel();
        jSeparator1 = new javax.swing.JSeparator();
        gauch = new hamroshare.customswings.GaugeChart();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);

        dashpanel.setBackground(new java.awt.Color(51, 51, 51));
        dashpanel.setPreferredSize(new java.awt.Dimension(162, 418));
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dashpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 270, -1));

        gauch.setBackground(new java.awt.Color(0, 0, 0));
        gauch.setForeground(new java.awt.Color(0, 255, 204));
        gauch.setColor1(new java.awt.Color(255, 0, 0));
        gauch.setColor2(new java.awt.Color(0, 153, 0));
        gauch.setGaugeSize(7);
        gauch.setValue(60);
        dashpanel.add(gauch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nepse Index:");
        dashpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Market Positivity");
        dashpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(dashpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(dashpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hamroshare.customswings.RoundPanel dashpanel;
    public static hamroshare.customswings.GaugeChart gauch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
